baseURL: "https://adam.dullage.com/"
languageCode: "en-gb"
title: "Adam Dullage"

module:
  mounts:
    - source: static
      target: static
    - source: node_modules/bootstrap-icons/font/fonts
      target: static/scss/fonts

markup:
  goldmark:
    renderer:
      unsafe: true
